name: test
on: [push]
jobs:

test_redis:
    runs-on: ubuntu-latest
    container:
      image: redis:7.0.4
    env:
     REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
     REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@v2.13.3


        with:
          image_name: 'redis:7.0.4'
          mode: 'start'
          
          command: |
            timeout 10 redis-server || true

  rezilion:
    needs: [test_runtimes, test_redis]
    runs-on: ubuntu-latest
    container:
      image: rezilion/validate-ci:b22238db

    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
      REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}
      REZILION_RUN_REMEDIATE: true
      REZILION_API_KEY: ${{ secrets.REZILION_API_KEY }}
      REZILION_BRANCH_NAME_UPLOADING_REGEX: ^main$

    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@v2.13.3
        with:
          mode: 'validate'
